# Generated by Django 5.1.4 on 2024-12-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_id_category_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='id',
        ),
    ]
